#!/bin/python
import os
from os import path

print("WELCOME TO THIS SHELL SCRIPT!!!\nMADE BY: SUMIT KUMAR")

access_token = input("Please Enter Your Github Access Token With Appropriate Permissions: ")

if path.exists(".env"):
    f = open(".env", "w")
    f.write(f"TOKEN={access_token}\n")
    f.close()
else:
    f = open(".env", "w")
    f.write(f"TOKEN={access_token}\n")
    f.close()